Binary(Left: Expr, Operator: Token, Right: Expr)
Grouping(Expression: Expr)
Literal(Value: any)
Unary(Operator: Token, Right: Expr)
Variable(Name: Token)
Assignment(Name: Token, Value: Expr)
Logic(Left: Expr, Operator: Token, Right: Expr)
Call(Callee: Expr, Paren: Token, Args: []Expr)
Function(Params: []Token, Body: []Stmt)
