Binary(Left: Expr, Operator: Token, Right: Expr)
Grouping(Expression: Expr)
Literal(Token: Token, Value: any)
Unary(Operator: Token, Right: Expr)
Variable(Name: Token)
Assignment(Name: Token, Value: Expr)
Logic(Left: Expr, Operator: Token, Right: Expr)
Call(Callee: Expr, Paren: Token, Args: []Expr)
Function(Keyword: Token, Params: []Token, Body: []Stmt)
Get(Object: Expr, Name: Token)
Set(Object: Expr, Name: Token, Value: Expr)
