Expression(Expression: Expr)
Print(Expression: Expr)
Var(Name: Token, Init: Expr)
If(Condition: Expr, Then: Stmt, Else: Stmt)
Block(Statements: []Stmt)
Loop(Condition: Expr, Body: Stmt, OnLoop: Expr)
Break(Keyword: Token)
Continue(Keyword: Token)
Function(Name: Token, Params: []Token, Body: []Stmt)
    Return(Keyword: Token, Result: Expr)
