Expression(Expression: Expr)
Print(Expression: Expr)
Var(Name: Token, Init: Expr)
If(Condition: Expr, Then: Stmt, Else: Stmt)
Block(Statements: []Stmt)
Loop(Condition: Expr, Body: Stmt, OnLoop: Expr)
Break(Token: Token)
Continue(Token: Token)
Function(Name: Token, Params: []Token, Body: []Stmt)
Return(Token: Token, Result: Expr)
